apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AmineBouzayeni/prod-manifests.git
    targetRevision: HEAD # Take the last commit of the repo
    path: manifests # The path in which the manifests are stored. Wa are going to track the prod ones
  destination: 
    server: https://kubernetes.default.svc # Local endpoint for Kubernetes cluster because we will deploy ArgoCD locally
    namespace: default # If you want argoCD to procede within a particular namespace. I will not do it, will only rely on default were my app is deployed
  syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true # If you want argoCD to create the namespace myapp for you

    automated:
      # selfHeal: true # If manual changes were done in the cluster ArgoCD will reverse them
      prune: true