name: Dockercoins app CI/CD
run-name: Dockercoins app CI/CD
on: [push]
env:
  CLUSTER_NAME: dockercoins-cluster-teo
  CLUSTER_ZONE: europe-west1-b
  PROJECT_NAME: teolia-school-devops
  TEST_NODE_IP: "35.205.50.30"
  HASHER_TEST_PORT: "30001"
  RNG_TEST_PORT: "30002"
  REDIS_TEST_PORT: "30003"
  WEBUI_TEST_PORT: "30004"
  GAR_LOCATION: europe-west1
  REPOSITORY: teolia-school-amineb


jobs:
  BuildAndPushImage:
    name: Build and push the docker image.
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: Get current version
        id: get_current_version
        run: |
          current_version=$(cat VERSION)
          echo "currentVersion=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_current_version.outputs.currentVersion }}
          release_name: Release ${{ steps.get_current_version.outputs.currentVersion }}
          body: |
            App version ${{ steps.get_current_version.outputs.currentVersion }}.
          draft: false
          prerelease: false

      - name: Get current branch
        id: current_branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Calculate image tag
        id: calculate_tag
        run: |
          currentBranch=${{ steps.current_branch.outputs.branch }}
          if [[ $currentBranch == 'main' ]]
            then
              tag=${{ steps.get_current_version.outputs.currentVersion }}
          else
            tag=${{ steps.get_current_version.outputs.currentVersion }}-${{ github.sha }}
          fi   
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Docker build
        run: |
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/hasher:${{ steps.calculate_tag.outputs.tag }}" hasher/
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/rng:${{ steps.calculate_tag.outputs.tag }}" rng/
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/redis:${{ steps.calculate_tag.outputs.tag }}" redis_server/
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/worker:${{ steps.calculate_tag.outputs.tag }}" worker/
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/webui:${{ steps.calculate_tag.outputs.tag }}" front/

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_KEY }}'
          token_format: 'access_token'
      
      - name: 'Docker login'
        uses: 'docker/login-action@v2'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'    
      
      - name: 'Docker push'
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/hasher:${{ steps.calculate_tag.outputs.tag }}"
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/rng:${{ steps.calculate_tag.outputs.tag }}"
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/redis:${{ steps.calculate_tag.outputs.tag }}"
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/worker:${{ steps.calculate_tag.outputs.tag }}"
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_NAME/$REPOSITORY/webui:${{ steps.calculate_tag.outputs.tag }}"
    outputs:
        imageTag: ${{ steps.calculate_tag.outputs.tag }}

  DeployTestingServices:
    name: Deploy testing instances of the services.
    runs-on: ubuntu-latest
    needs: BuildAndPushImage
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Install gcloud authentication plugin
      run: |
        REPO_URL="https://packages.cloud.google.com/apt"
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

        sudo apt-get update -y
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_KEY }}'
        token_format: 'access_token'

    - name: Authenticate to GKE cluster
      run: |   
        gcloud container clusters get-credentials \
        ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_NAME }}

    - name: Update the image tag
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["manifests/test/*"]'
        tokenPrefix: __
        tokenSuffix: __
      env:
        TAG: ${{ needs.BuildAndPushImage.outputs.imageTag }}
        GAR_LOCATION: ${{ env.GAR_LOCATION }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        REPOSITORY: ${{ env.REPOSITORY }}  

    - name: Deploy to the gke cluster
      run: |
        kubectl apply -f manifests/test

    - name: Replace the URI in the test file
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["hasher/tests/smoke_test.rb", "redis_server/tests/smoke_test.py", "rng/tests/smoke_test.py"]'
        tokenPrefix: __
        tokenSuffix: __
      env:
        IP: ${{ env.TEST_NODE_IP }}
        HASHER_TEST_PORT: ${{ env.HASHER_TEST_PORT }}
        RNG_TEST_PORT: ${{ env.RNG_TEST_PORT }}
        REDIS_TEST_PORT: ${{ env.REDIS_TEST_PORT }}
        WEBUI_TEST_PORT: ${{ env.WEBUI_TEST_PORT }}

  RunHasherTests:
    needs: DeployTestingServices
    name: Run smoke tests on the Hasher component
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Replace the URI in the test file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["hasher/tests/smoke_test.rb"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          IP: ${{ env.TEST_NODE_IP }}
          HASHER_TEST_PORT: ${{ env.HASHER_TEST_PORT }} 
      
      - name: Run the hasher component smoke tests
        run: |
          ruby hasher/tests/smoke_test.rb

  RunRngTests:
    needs: DeployTestingServices
    name: Run smoke tests on the Rng component
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
    
      - name: Replace the URI in the test file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["rng/tests/smoke_test.py"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          IP: ${{ env.TEST_NODE_IP }}
          RNG_TEST_PORT: ${{ env.RNG_TEST_PORT }}
      
      - name: Run the rng component smoke tests
        run: |
          echo "Installing some prerequisite to run tests"
          pip install pytest

          echo "Running Smoke Tests for the Rng component"
          cd rng && pytest

  RunRedisServerTests:
    needs: DeployTestingServices
    name: Run smoke tests on Redis Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Replace the URI in the test file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["redis_server/tests/smoke_test.py"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          IP: ${{ env.TEST_NODE_IP }}
          REDIS_TEST_PORT: ${{ env.REDIS_TEST_PORT }}
        
      - name: Run redis server component smoke tests
        run: |
          echo "Installing some prerequisite to run tests"
          pip install pytest redis
          
          echo "Running Smoke Tests for Redis Server component"
          cd redis_server/ && pytest

  RunWebUIIntegrationTests:
    needs: DeployTestingServices
    name: Run webui component integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Run webui component integration tests
        run: |
          echo "Running Smoke Tests on the Webui component"
          response=$(curl -s -o /dev/null -w "%{http_code}"  http://${{ env.TEST_NODE_IP }}:${{ env.WEBUI_TEST_PORT }}/)
          if [[ $response != 200 && $response != 302 ]]
            then
              echo "Smoke test against the test deployment failed againt / endpoint with code ${response}"
              exit 1
            else
              echo "The smoke test againt / passed"  
          fi
          response=$(curl -s -o /dev/null -w "%{http_code}"  http://${{ env.TEST_NODE_IP }}:${{ env.WEBUI_TEST_PORT }}/json)
          if [[ $response != 200 ]]
            then
              echo "Smoke test against the test deployment failed againt /json endpoint with code ${response}"
              exit 1
            else
              echo "The smoke test against /json passed"  
          fi  
  CleanUpTestDeployment:
    needs: [RunHasherTests, RunRngTests, RunRedisServerTests,  RunWebUIIntegrationTests]
    name: Delete the testing deployments and services
    runs-on: ubuntu-latest
    steps:       
    - name: Install gcloud authentication plugin
      run: |
        REPO_URL="https://packages.cloud.google.com/apt"
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

        sudo apt-get update -y
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_KEY }}'
        token_format: 'access_token'
    
    - name: Authenticate to GKE cluster
      run: |   
        gcloud container clusters get-credentials \
        ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_NAME }}

    - name: Delete test pods and services
      run: |
        # Delete pods
        echo "deleting pods"
        kubectl delete deployment hasher-deployment-test
        kubectl delete deployment redis-deployment-test
        kubectl delete deployment rng-deployment-test
        kubectl delete deployment worker-deployment-test
        kubectl delete deployment webui-deployment-test
        # Delete services
        kubectl delete svc hasher-test-service
        kubectl delete svc redis-test-service
        kubectl delete svc rng-test-service
        kubectl delete svc webui-test-service

  UpdateManifestsWithNewTags:
    name: Update Manifests repo with the new Tags in order to be executed by ArgoCD
    runs-on: ubuntu-latest
    needs: [BuildAndPushImage, RunHasherTests, RunRngTests, RunRedisServerTests,  RunWebUIIntegrationTests]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          repository: 'AmineBouzayeni/prod-manifests'
      - name: Update tag in the Kubernetes manifest files
        env:
          GA_KEY: ${{ secrets.GA_KEY }}  
        run: |
          git remote -v
          mkdir ~/.ssh
          echo "$GA_KEY" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_ed25519
          git remote set-url origin git@github.com:AmineBouzayeni/prod-manifests.git
          git config --global user.name "runner"
          sed -i -e "/^\([[:space:]]*image: \).*/s//\1europe-west1-docker.pkg.dev\/teolia-school-devops\/teolia-school-amineb\/hasher:${{ needs.BuildAndPushImage.outputs.imageTag }}/" manifests/hasher-manifest.yml
          sed -i -e "/^\([[:space:]]*image: \).*/s//\1europe-west1-docker.pkg.dev\/teolia-school-devops\/teolia-school-amineb\/redis:${{ needs.BuildAndPushImage.outputs.imageTag }}/" manifests/redis-manifest.yml
          sed -i -e "/^\([[:space:]]*image: \).*/s//\1europe-west1-docker.pkg.dev\/teolia-school-devops\/teolia-school-amineb\/rng:${{ needs.BuildAndPushImage.outputs.imageTag }}/" manifests/rng-manifest.yml
          sed -i -e "/^\([[:space:]]*image: \).*/s//\1europe-west1-docker.pkg.dev\/teolia-school-devops\/teolia-school-amineb\/worker:${{ needs.BuildAndPushImage.outputs.imageTag }}/" manifests/worker-manifest.yml
          sed -i -e "/^\([[:space:]]*image: \).*/s//\1europe-west1-docker.pkg.dev\/teolia-school-devops\/teolia-school-amineb\/webui:${{ needs.BuildAndPushImage.outputs.imageTag }}/" manifests/webui-manifest.yml
          git add -A
          git commit -m "Update image tag to use ${{ needs.BuildAndPushImage.outputs.imageTag }}"
          git push origin main